

statuses = {0: {'file': '0.gif', 'label': 'tornado', 'title': 'Tornado'},
 1: {'file': '1.gif', 'label': 'tropical storm', 'title': 'Tropical Storm'},
 2: {'file': '2.gif', 'label': 'hurricane', 'title': 'Hurricane'},
 3: {'file': '3.gif',
     'label': 'severe thunderstorms',
     'title': 'Severe Thunderstorms'},
 4: {'file': '4.gif', 'label': 'thunderstorms', 'title': 'Thunderstorms'},
 5: {'file': '5.gif',
     'label': 'mixed rain and snow',
     'title': 'Mixed Rain And Snow'},
 6: {'file': '6.gif',
     'label': 'mixed rain and sleet',
     'title': 'Mixed Rain And Sleet'},
 7: {'file': '7.gif',
     'label': 'mixed snow and sleet',
     'title': 'Mixed Snow And Sleet'},
 8: {'file': '8.gif',
     'label': 'freezing drizzle',
     'title': 'Freezing Drizzle'},
 9: {'file': '9.gif', 'label': 'drizzle', 'title': 'Drizzle'},
 10: {'file': '10.gif', 'label': 'freezing rain', 'title': 'Freezing Rain'},
 11: {'file': '11.gif', 'label': 'showers', 'title': 'Showers'},
 12: {'file': '12.gif', 'label': 'showers', 'title': 'Showers'},
 13: {'file': '13.gif', 'label': 'snow flurries', 'title': 'Snow Flurries'},
 14: {'file': '14.gif',
      'label': 'light snow showers',
      'title': 'Light Snow Showers'},
 15: {'file': '15.gif', 'label': 'blowing snow', 'title': 'Blowing Snow'},
 16: {'file': '16.gif', 'label': 'snow', 'title': 'Snow'},
 17: {'file': '17.gif', 'label': 'hail', 'title': 'Hail'},
 18: {'file': '18.gif', 'label': 'sleet', 'title': 'Sleet'},
 19: {'file': '19.gif', 'label': 'dust', 'title': 'Dust'},
 20: {'file': '20.gif', 'label': 'foggy', 'title': 'Foggy'},
 21: {'file': '21.gif', 'label': 'haze', 'title': 'Haze'},
 22: {'file': '22.gif', 'label': 'smoky', 'title': 'Smoky'},
 23: {'file': '23.gif', 'label': 'blustery', 'title': 'Blustery'},
 24: {'file': '24.gif', 'label': 'windy', 'title': 'Windy'},
 25: {'file': '25.gif', 'label': 'cold', 'title': 'Cold'},
 26: {'file': '26.gif', 'label': 'cloudy', 'title': 'Cloudy'},
 27: {'file': '27.gif',
      'label': 'mostly cloudy (night)',
      'title': 'Mostly Cloudy (Night)'},
 28: {'file': '28.gif',
      'label': 'mostly cloudy (day)',
      'title': 'Mostly Cloudy (Day)'},
 29: {'file': '29.gif',
      'label': 'partly cloudy (night)',
      'title': 'Partly Cloudy (Night)'},
 30: {'file': '30.gif',
      'label': 'partly cloudy (day)',
      'title': 'Partly Cloudy (Day)'},
 31: {'file': '31.gif', 'label': 'clear (night)', 'title': 'Clear (Night)'},
 32: {'file': '32.gif', 'label': 'sunny', 'title': 'Sunny'},
 33: {'file': '33.gif', 'label': 'fair (night)', 'title': 'Fair (Night)'},
 34: {'file': '34.gif', 'label': 'fair (day)', 'title': 'Fair (Day)'},
 35: {'file': '35.gif',
      'label': 'mixed rain and hail',
      'title': 'Mixed Rain And Hail'},
 36: {'file': '36.gif', 'label': 'hot', 'title': 'Hot'},
 37: {'file': '37.gif',
      'label': 'isolated thunderstorms',
      'title': 'Isolated Thunderstorms'},
 38: {'file': '38.gif',
      'label': 'scattered thunderstorms',
      'title': 'Scattered Thunderstorms'},
 39: {'file': '39.gif',
      'label': 'scattered thunderstorms',
      'title': 'Scattered Thunderstorms'},
 40: {'file': '40.gif',
      'label': 'scattered showers',
      'title': 'Scattered Showers'},
 41: {'file': '41.gif', 'label': 'heavy snow', 'title': 'Heavy Snow'},
 42: {'file': '42.gif',
      'label': 'scattered snow showers',
      'title': 'Scattered Snow Showers'},
 43: {'file': '43.gif', 'label': 'heavy snow', 'title': 'Heavy Snow'},
 44: {'file': '44.gif', 'label': 'partly cloudy', 'title': 'Partly Cloudy'},
 45: {'file': '45.gif', 'label': 'thundershowers', 'title': 'Thundershowers'},
 46: {'file': '46.gif', 'label': 'snow showers', 'title': 'Snow Showers'},
 47: {'file': '47.gif',
      'label': 'isolated thundershowers',
      'title': 'Isolated Thundershowers'},
 3200: {'file': '3200.gif',
        'label': 'not available',
        'title': 'Not Available'}}